"""baseline schema: deploys signals incidents evidence jobs

Revision ID: e9046a0c0243
Revises:
Create Date: 2026-07-04 14:26:37.427643

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e9046a0c0243"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deploys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("head_sha", sa.String(length=40), nullable=False),
        sa.Column("previous_head_sha", sa.String(length=40), nullable=True),
        sa.Column("branch", sa.String(length=255), nullable=True),
        sa.Column("conclusion", sa.String(length=32), nullable=True),
        sa.Column("run_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_deploys_head_sha"), "deploys", ["head_sha"], unique=True)
    op.create_table(
        "incidents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("release", sa.String(length=64), nullable=True),
        sa.Column("correlation_key", sa.String(length=255), nullable=True),
        sa.Column("severity", sa.Integer(), nullable=True),
        sa.Column("deploy_id", sa.Integer(), nullable=True),
        sa.Column("verdict", sa.String(length=16), nullable=True),
        sa.Column("ranked", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("brief_message_id", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["deploy_id"],
            ["deploys.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_incidents_correlation_key"),
        "incidents",
        ["correlation_key"],
        unique=False,
    )
    op.create_table(
        "evidence",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("incident_id", sa.Integer(), nullable=False),
        sa.Column("commit_sha", sa.String(length=40), nullable=True),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("cited", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_evidence_incident_id"), "evidence", ["incident_id"], unique=False
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("incident_id", sa.Integer(), nullable=True),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "signals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("dedup_key", sa.String(length=255), nullable=False),
        sa.Column("release", sa.String(length=64), nullable=True),
        sa.Column("fingerprint", sa.String(length=255), nullable=True),
        sa.Column("frames", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("count", sa.Integer(), nullable=True),
        sa.Column("users", sa.Integer(), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("incident_id", sa.Integer(), nullable=True),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_signals_dedup_key"), "signals", ["dedup_key"], unique=True)
    op.create_index(
        op.f("ix_signals_incident_id"), "signals", ["incident_id"], unique=False
    )
    op.create_index(op.f("ix_signals_release"), "signals", ["release"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_signals_release"), table_name="signals")
    op.drop_index(op.f("ix_signals_incident_id"), table_name="signals")
    op.drop_index(op.f("ix_signals_dedup_key"), table_name="signals")
    op.drop_table("signals")
    op.drop_table("jobs")
    op.drop_index(op.f("ix_evidence_incident_id"), table_name="evidence")
    op.drop_table("evidence")
    op.drop_index(op.f("ix_incidents_correlation_key"), table_name="incidents")
    op.drop_table("incidents")
    op.drop_index(op.f("ix_deploys_head_sha"), table_name="deploys")
    op.drop_table("deploys")
    # ### end Alembic commands ###
